FROM continuumio/miniconda

# set up env.
RUN apt-get install build-essential -y

# set up working dir.
WORKDIR /home/dev/

# copy code.
COPY ./*.py ./
COPY ./configs/requirements.txt ./

# copy data.
RUN mkdir data
COPY ./data/ ./data/

# install packages.
RUN pip install -r requirements.txt

# expose port.
EXPOSE 5000

# run server.
CMD python api.py
